# Internal access to Seerr web UI
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seerr-internal
spec:
  hostnames:
    - "seerr.${SECRET_DOMAIN}"
  parentRefs:
    - kind: Gateway
      name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: seerr
          port: 5055
      matches:
        - path:
            type: PathPrefix
            value: /
---
# External access via Cloudflare Tunnel
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seerr-external
spec:
  hostnames:
    - "seerr.${SECRET_DOMAIN}"
  parentRefs:
    - kind: Gateway
      name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: seerr
          port: 5055
      matches:
        - path:
            type: PathPrefix
            value: /
