apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:qvh7xa/HorF6sSMISDTNp+aFCUbetfuckCKKDwEWcxK4eoEYZq+UTg==,iv:vBALrKQb3xvotfLD5OZ+AO/fqfEamSl9tqeIg9n7Jbk=,tag:8gf83RRChUpX8LFZS8KVfA==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TC9HemZlNGgyTktqOUV1
        biswaXJqWVZsSzhCQnMxZFFzYXgwWUx6ZWtnCkVxZE9Jb1IrcUZVYW5iYkxyRThz
        MGppOXJPK2VwczVwbW90clk5dk1RZXMKLS0tIE5FMXlXNFZUVDR0L0VmTWxLUFNj
        dW5mN0tPQWw0MklGK3Vka0gxNXAxVlEKv6Dlg7bbM8u/Wi/nq+aPMzxv3LBTAFSk
        5VSL7cUfjv2qP+Q0U7ZtXPBUdGTe1JwPgikxktQrzbEg0Bj8cUOX7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T02:03:30Z"
  mac: ENC[AES256_GCM,data:JlKDLJs5tUY/dDlmvwUchIBETLSMsM+myJrgrz2VW0efpP2kwDHF9EzAZHdJB9R4K5x4HQjfNWUOKIe69vfQDmstjJUbKtnI78MRyVx7DKup8QvkdfkklmYgoDdG1UZBB0RL2E2LYDYSNs7NgYYMly+wra32pP2RBhlZF4Ayz/Q=,iv:Sy+ffcJRnJxUpZ6Vy5XKSsYJIC5jPaCs2V6nhaDCoKI=,tag:zx66V3iDHrhS9W4X0F7xYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
