apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:oZ9gID6+2RKfAlMks/tB8758m1Jcn5BDChKi7n1ongN4W+gUGOFoFg==,iv:3a127ccZbO5uARzgttqGdUDAVYkSsRbU5z1HvYhjmls=,tag:w8FnkpGLkE7n+6/sGuOwlA==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeTd6Y0VVU3BVT2IxUE84
        d01WcWQwUkVSbjgxSEJocGpFTy93ODBmaEdFCktiaXNwNWpEdjFmb1JiWS9JTEpB
        bW5NOUxqV1g2aGorbGo1Z1VnZnJyRUUKLS0tIEtaZ25DVEdhVENLK0lDTGcxelRS
        RG9sZmRyOGc3cXVJdTBvWkY3VHUzRTAKU1TaDavJU+f8XhlRZ1eqPY3OauGbXKPC
        2jVjr+6PKrdL9Mv08L0PpVBEdIZAnKGe8usIilxSGmpowejfVHuq5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T20:42:56Z"
  mac: ENC[AES256_GCM,data:pu5sEDUoS0NEPcT9pC8wgQisTAbMrkfs/eGIXot47Lh0T7CAQ6IREmwHqokrtJ/NR9qs0t3RHbuJe87nU8d+/wWwEZyGxN8dtJpoCgk7BZmat6ia/ZnISzwBSm2WvL4X8x2y2jHIV8T4bcJxvVzvglxBPmkYA/gG6trE/6XXYRU=,iv:UIOxeY/dhZ1aY1IOjBA2kp6NsiC+DXMK2fx1S81tmmw=,tag:UjXJGkQ21m40ODUpH44ofA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
