apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:pXdi/PjpZZLnVlh41HrwizGNo0mfF2S+vDkR3n0oLPM20w8Z7evy7w==,iv:vI3WXnWt3rVnzrQ+OnQwELLckczzPj2DjThgEm3SBBs=,tag:IoBj85tpbD7NtLk1KuC2Tg==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSGNSWGlCcjZ5bUw5WnJF
        NU5XUm9KaUVoQTBBZkVoZU9sUUE0VndJQm1ZCmFqQ09iUFVrSGY2eXZvcVRjV3pT
        Nk01K29CTnlINU11US90V0ZQQmMyb2cKLS0tIFhreTdQTG4wZDhnL1VqeWdLcHZO
        VThialYvZlRLSVBjU3dPS2R1bFBGdTAKH2P7WEeGHD6og6TUnTQXO4m/LH9mdiLd
        y7bMMT8fCqxzck1bIFJGYq7OQIaIzc69DYDXOdk+L8fhaIgGlzHX+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T03:31:54Z"
  mac: ENC[AES256_GCM,data:ZE0cL/m6vZCpVGdd5y9YOkXTLZ/1v1Kly0wT40Zwg034LG1k1A9b89R7iwN8oGkhBgdIQo6JKdnN2k5+sMayXLZp9gI+PMZVQBbNk3JfKtGeQ55chXhXM0lbvmQSeK2jCYGTKh4Y+H7DVaY9Mmo9564FEv8r3zdbJeK+2TH7bPU=,iv:33CkFGXIOOWr9t5T4BL77iipHXZpsg9HhvFUsFRty3U=,tag:Ejir0N9wyN6vJtjPK94rzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
