# Internal access
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin-internal
spec:
  hostnames:
    - "jellyfin.${SECRET_DOMAIN}"
  parentRefs:
    - kind: Gateway
      name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: jellyfin
          port: 8096
      matches:
        - path:
            type: PathPrefix
            value: /
---
# External access via Cloudflare Tunnel
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin-external
spec:
  hostnames:
    - "jellyfin.${SECRET_DOMAIN}"
  parentRefs:
    - kind: Gateway
      name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: jellyfin
          port: 8096
      matches:
        - path:
            type: PathPrefix
            value: /
