apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:lDi1JrRV7Y3M,iv:WqAxQOCg3mfutP3jn4ZZpL6YNg+3l3Ad4uAc7sizCSI=,tag:HZBoLlrOijxK6NSAlaIeUw==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQW8xMEtYbHY2dXZtbTRI
        RlFDMUxlR3dORDZUUC80L25abWRMcTVOK3pvClJ1RXFJNExObDlsOXhyS2tXbGZx
        ZWQvMGFpUDNpNndrUUluN2sxYjNrZGsKLS0tIFlSK092VzRPdGpOVkcxMngrRnpB
        WWQ3OW1BblVjcGVmZ1NPbEtmYzRXVjAKssUKeRn7zFlQvKQJvoI6FOsrQA0BkjLp
        ZTBumq92rfHNrOiATbfFgq1yiP8ZGMazK4E4NYVt5bu4zKVPJ3rsZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T02:03:30Z"
  mac: ENC[AES256_GCM,data:pcSGdsaxivr88Wswx9V8F5/gc6LBn9Z55qC+5an4Km/tnFsQ97yOXc9u/4hhw0CL7Rgien4nGGbW95ZVZfEkj3LE0Js5KuFPt5a9Hvigy3nxIFE+sgAc1mYNeHs6w9Sv/rrXBfDaTMETwX00BSOSBZlBTEsv+U2MquULpT5FkK0=,iv:XoIKEHhXuOMx9mjpkOfYb2Uc7QpynqikJ7hFtIoUKW8=,tag:D9SXHaz8SdqyCPjvpgHWcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
