apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:IMGwUNOXr3SB,iv:o+se5C/bBAer1N1UY5dWQ5vbmAam3ZKOfZIuPOQWk9E=,tag:oUrt0XjVI41WNpswnoLo/w==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWGxFd1RoMjNJWC93alJp
        NUdpRFU2dTRaWTVHMTBLaEd6Z0ozeHljZWtzCmdyOC9wYmtKNThPUUdicllaYUxR
        aEQxQStpbVNpNXU3Z2M3Uk9YdWpvNGcKLS0tIHpIZUd6T0lHVDBUVGl3QWdDK3NU
        QWdzbTRiZjlEbmNHSlZ4NWJONG5TVE0KMEGOcBxhDwo9LziSlSC+SV9EhqvVefE+
        DYulJeoWlBDjRYi0i8l8/fXC5tqrJI4H3sGgr+dsca7I0i6Yhuubkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T03:31:54Z"
  mac: ENC[AES256_GCM,data:QhUwH4w0/qYYaNzxTqvXWhKhS/xactgParfZPAscxb63Yz8lxzYu0LcfvXRDF4nN8Xi3xAXK82dl1tqmiWiHw853oomOU32NcilNgf8QmWOyCk3/gFGp80Ms/QOi8ToxbbOGK6rdG2XceTTbTeY8mp7/IsnxnWKbb9YerjoMrlU=,iv:O9CxfeZal5RCQYHHXMXO6TcWaWsmzj71zQ3ESgy41tA=,tag:1B0wPcrzB5uErinLCf5fdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
