apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:qvnuRcasRF9m,iv:0EX3xcWplLNUhEV0wOkcW2Us2yPXCQ1naIDUAUoAUko=,tag:tMg2XSjDC51VfJwJPZfteg==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTzdMOWpOT1RUME9LbG5m
        SlBXeTVoMHAvL0NqZFpmSmxaYXNXR2dVNWd3CnZqWWdTSncrZjhtZWUvS2NCZGVG
        SnNVTVRKN2FRQzF0S0lWVmI1R01LRU0KLS0tIE45RXh5TzNiOGVkNDE1Y2VweGNz
        TG94SE5HK3ZwOFU4M3k4YU9XUTdZeTAKtjx8T9ePjYEXrU9+FMbC+dZc/IkR7kbm
        ++KuTdCYxstUhhiaguMLzBUdtfUhQ16u1x7oaz9b9lEXn+j5nttxIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T20:42:56Z"
  mac: ENC[AES256_GCM,data:wtKbCRH9iI0e4km8JzCNfbcUtp6RJM0zzc/K/qmiIdGhfcURDRQ+facXFa0HvMtp+l9bd1KrCLLGhkLC+EZm1uDgKoQ85m5bHlDDTFskJVpf42q2bsJnGsNjDUaaiz66YCrD0iegWemqjGjpiNQAivkTzAVT8Ai+hvKZQHWpLfA=,iv:LDfwj+ZchWs2qoRd4oyhZoHQn55PTZDyWNfuhgfdbos=,tag:z+gyPWYd0n7xrRZo/uXccw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
