apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:IMGwUNOXr3SB,iv:o+se5C/bBAer1N1UY5dWQ5vbmAam3ZKOfZIuPOQWk9E=,tag:oUrt0XjVI41WNpswnoLo/w==,type:str]
  SECRET_NAS_IP: ENC[AES256_GCM,data:IfQC6ZtMOL+2q6sS7sQ=,iv:vKiJ1W6HDb+6YmFjd0rZ0e7N8K6f92BavseBGWKDvD8=,tag:c8u0kiFq7dQGRDLxiG65Aw==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWGxFd1RoMjNJWC93alJp
        NUdpRFU2dTRaWTVHMTBLaEd6Z0ozeHljZWtzCmdyOC9wYmtKNThPUUdicllaYUxR
        aEQxQStpbVNpNXU3Z2M3Uk9YdWpvNGcKLS0tIHpIZUd6T0lHVDBUVGl3QWdDK3NU
        QWdzbTRiZjlEbmNHSlZ4NWJONG5TVE0KMEGOcBxhDwo9LziSlSC+SV9EhqvVefE+
        DYulJeoWlBDjRYi0i8l8/fXC5tqrJI4H3sGgr+dsca7I0i6Yhuubkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:51:36Z"
  mac: ENC[AES256_GCM,data:UNVpoNivuP+xO0SKDg7jzSw5m2kbGIt2XbHBbhgj4GYUxHXV8ZY7J6w2q1hUAXD4BpFrdMf+84iVKwS5Tj0Jt2jlNEN3dyoFE3HyhiXoNu0tBt7vm0u5YR1Ln4mcS4d3RT2mA46R331ssIJQkUF5xEwQTRZwgz4p/6WXMlcGcQY=,iv:8z8PsiRq5BY+D0vTyLWYITZCHJg5Zq+wpAYCNziIUOo=,tag:6C8ozP/WMhPty2Lt5+bjsw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
