apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:A8dcF/2nAUf0g7N80EF0MBiHqVzZpCwZ+PLJF+88dm4=,iv:mcdp9vEsqNE8+ulf8VhzankuUARbUxfsBOPh2APkZak=,tag:wRIr8HwE5/8V1bZKq7BaoQ==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bHRqT0lJT2hnZmRHVjRw
        YkZKUGZxU1FJaWhBNzhVcnNuY0dvaEZFY1NNCjJWMzBWdXhod2VMaVhOL21VWFRt
        SXB4ZDFEa08rVE9HK1hHNmZFZ1JZaVEKLS0tIHNlS1pGNmNKWlVOcE5IalFKRkNP
        WFhveGxDSk1wNnB3NXJpYTRKOW9GUjAKFkRtWKmSXv2W+06T+Yo5OwjZ2qIrFjgM
        O2gPkLbEmRXRu7EgcXGurKfVAwP8ijDWuFuJydjieV/Aoa7MO0/Gew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T02:03:30Z"
  mac: ENC[AES256_GCM,data:cbyhMpxysj261TA8iih6d/Fh82I1OERpXYNAx2n6nCixUeXK9SlW6zZcUuSpFSr9auF7SzKDj/Ddr/7bwTfXwrRna+1uJvvyQlcAIPR7As3dSO3lOER81vvGwTyUrRqgSXSj9In8EzbPIpBHKHTvHK1iAsm02d3w6iR31Xguae4=,iv:JuNz0Z6hJPUgLTKYvYOIir/QIcGtmLtkSQfegVVZxYA=,tag:guI78ABXICkcgBHFTVhq7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
