apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Yp8HzU8Ail7NVhibCf5+DdMSH+OXP0dhNJ4zsdYtZLs=,iv:QYmhzBhmxVsVJ3dmRZmD8kP0SAR2WOOFjavaSQytTHg=,tag:KPMtU0TAr5UUJ5cmeO2HMw==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbk1Tbms4MzdpOWNZK1NC
        QmdrTVdwOVBYeTIyVFRSY3ZIRlprNXRaTGxFClhzSUJ6VDNuNkJFekE3TWdyMlhq
        cUc3YmIxTXMzeWNhaHFWTFlqM0wwRE0KLS0tIHVnZ2RUaHRmUldGdUwrcTdpTXNO
        dmZ0RkRablcxc1NZcXZTQk9YUkhmcmsKUJ+Tzq9td9O8C8mxJOHf3q5HjV1Bn081
        8RHXNNMej+mFpIWXY83NmBCSESpv7Rm1V/Ds+o8hu1sc199ZWwkO/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T03:31:54Z"
  mac: ENC[AES256_GCM,data:RBqxaHVGe4vLaUOvhT8tCYxo7leQRZAaGYdV9bHxVPaIlK9lt2BTWyHik73GibGMdxHhMDAhog8Kx8ZcIfo6K7VU/D5aJ1vlwgZr0tVQkXAWPvv9wTXeo90cRN/6G8+D4lMS/onNHuScoGaBtnt0wJtMvij7EO1JZ0KF0GbXGrk=,iv:zhkd6TlX1S52OyYdxmsyE+h6/0o4Ke5nBvmsvcH7Wes=,tag:uKTwD7dFah464S3xXt38EA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
