apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:o2Umf/L1h3iHkKdbTcscnMJA/sRituAA2MXgv2FhgEY=,iv:b6z3ZOoBsdFtwg7VmcsOxLBO1VSxfMoFNieP51SGl2Y=,tag:aPUQ2OZa0lcLg0413kb5nA==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcWlSMGhpWm0wWkRLMlNB
        ZW1iOXo0OU9zN2Z0TWxHdFlGZVlrN2VJMFhFCnJBNlZPdzRXWlM0OWFpUVVJNzJ3
        ZEdjWmdmeGhIcGFrdzV6N29VZW85TjAKLS0tIEJRNjhsMEpNTEdRVlJnMjdlRUpX
        b2k0WWo3eVJJVUtnOTQ5eC9UNTRiVXcKRKakYpOdtNT4RoMOC5Rw9aGitFWlpNKs
        NVFMhAs2OcCpu+SJaKIT2HP5wgC0vddpZRtyL/sly+IexQnnQLNlLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T20:42:56Z"
  mac: ENC[AES256_GCM,data:p7nKz0349j4cjCKXt6NEzXEigMS9KPxLHjXbNyS8x1jUfR2BAH76OO///+VO5PdWs/00TBLk2xN6Da87dOS96Yv40yO0jH/5YvgRDb6lQYdKMxgFK91cvnmh6vfprZZk9vFNer73awYZf4+jiFIr+vOaz3Wb8gkOAgKwdSfSZEg=,iv:gAEh4d8zLs0EJGII36Sm/l5f5NVz60WJNioWJQOg14k=,tag:cVA9IbzThGSAyX6xZd2NTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
