# PVC for qBittorrent config (stored on Ceph for persistence)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# PVC for media library (TrueNAS NFS)
# All media apps share this mount for hardlink support
# Structure: /media/downloads, /media/movies, /media/tv
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-media
spec:
  storageClassName: truenas-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Ti
