# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
#
# This ExternalSecret fetches the Grafana admin password from 1Password.
#
# Prerequisites:
#   1. Create an item in 1Password called "grafana"
#   2. Add a field called "password" with your desired admin password
#
# The secret created will have:
#   - admin-user: "admin" (hardcoded)
#   - admin-password: <fetched from 1Password>
#
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  # How often to sync the secret from 1Password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    # Name of the Kubernetes Secret to create
    name: grafana-admin
    template:
      engineVersion: v2
      data:
        # Grafana expects these exact key names
        admin-user: admin
        admin-password: "{{ .password }}"
  data:
    # Fetch "password" field from "grafana" item in 1Password
    - secretKey: password
      remoteRef:
        key: grafana
        property: password
