---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-config
data:
  config.json: |
    [
      {
        "clusterID": "4e4b1300-aa61-4c18-9edc-348a3e77d6ef",
        "monitors": [
          "192.168.20.201:6789",
          "192.168.20.202:6789",
          "192.168.20.203:6789",
          "192.168.20.204:6789",
          "192.168.20.205:6789"
        ]
      }
    ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-encryption-kms-config
data:
  config.json: "{}"
