---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ceph-rbd-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ceph-rbd-secret
    template:
      engineVersion: v2
      data:
        userID: kubernetes
        userKey: "{{ .credential }}"
  data:
    - secretKey: credential
      remoteRef:
        key: ceph_kubernetes_client
        property: credential
