# Internal access to Immich web UI
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich-internal
spec:
  hostnames:
    - "immich.${SECRET_DOMAIN}"
  parentRefs:
    - kind: Gateway
      name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: immich-server
          port: 2283
      matches:
        - path:
            type: PathPrefix
            value: /
---
# External access via Cloudflare Tunnel
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich-external
spec:
  hostnames:
    - "immich.${SECRET_DOMAIN}"
  parentRefs:
    - kind: Gateway
      name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: immich-server
          port: 2283
      matches:
        - path:
            type: PathPrefix
            value: /
