apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:HHdm1uedriZIcG2YQrQJPHHJS6Gefrz1mE1jaexC8QXyAP10WfAWBymvD+Ums4Molq1DHV3YZCWlKpojAMoB6HUtViKa5EQfvmHK/YaEhiGrVjagX6WAVNK4J14S61L65t+gQIt8eMC4euZUEs70nITamP0QIwWhPWVyO9FZdxl/IDJhs+MOITyiCrvZwQdFuu5QNJTgkXgflM0QIGtYR7WBe0+QnQyFxMmuJxpVHzFepRsi,iv:QldP9E12lHaDG6Fl64ObI28NWd3U9otX6qmZE1ag27U=,tag:bHr8kawhVgL91J6nKTA1RA==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SWxjZjJJcWZzNjYvU1F0
        dHgyYUZDSVVpdGtjeE5uVDM1UEdFczBjdVhRCmNna3BzUTcyVHBKYlQ3MWtFWkF0
        SEUxMFczaDMxdjFLY21UdG9QWjVSckkKLS0tIDBPVDdCeFRtNzlDdEt6SEJGUzN3
        TGNDUDBBWlN6cW9xZmM5am5jUjE2SDAK97YVMz9M+awZ8ULA7eOFzobK1PTU9Gyu
        wUPVZ1yRtUjVuzvMp80sFoX+G5KgDUFOysDT2p0harvv6bGPiL92mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T03:31:54Z"
  mac: ENC[AES256_GCM,data:P5/+XGUAEDXzC20gxtqCxAT8vqxC2kCo9rAVjLNM87CwYyGixRS5InVbvgYSdqhUSzmVZT1kTA78oteKsTPe9YEOAu1O4pRqujXKE2g7E4hemW5P6a+ayZlO0BJmiOZfhOQl2wymF+8J4iUvdWdGOrCd2El7QVfRPWQD4H4I+6E=,iv:sdpQbIZRBJdR2ebSzSQ9IE1fT3vPSYm1snwk1flDGF0=,tag:/rafmx645A5b2uwBpjuFTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
