apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:4W7k9Us+vSTSVGqRRMsDuRnsAekNFFSLFkkrhXWKp8cACpSvyzHH4UkXuZS87o+acY2ypPRsaMJsR5S9Kfhh+unBQ1X6ISjAaZRjYGUgMFE71h7+kVvYaUxxtYPdBZ98mC8AMd1xleV/dTz010iGyQnDU6tj0dUjKHf0h8/N+yqZl419INuO4vBlEtWSROdYDUCFcCYtkOCNPwq6gLV+JLyLR27lnB6X6kfVlsmj8aDvuwr1,iv:JVeHECW8NORybk3/2lMF/kyCQPNN2EWHTe6mjQZ+GFE=,tag:YD23PhDDrnbwxt6FjQB/xQ==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbFJVRjhsbllTWUdGUU5G
        VXhWeGo2YVhhUUswVm9DVFJ5RTQ4K1pBSUJjCkxvZWVFMHZJZXVhZUhUcUI2Zngy
        UHJVNDVPU0UwYmVTUmRJZENPV3h1N3MKLS0tIFJrOThPN3NLNU9RYW9MK0VMTEJo
        UXVLdDZ6YTFPa2tIRFppNFlyZjFJR00KZa1b6JGjNr/raKVyEEQy1eV9Z6+Qr8oo
        ZHQPTo4XAGN6y5GSAa4EHfr2UoRxaREHhc8w0fFDaA0nvq2diY26kQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T02:03:30Z"
  mac: ENC[AES256_GCM,data:khyFbgwOm/tMxznlH7huNjtlEaTVk4lI+IpXHGF9+oimrPoFbgQna+1sA89SWRib4FlXWYdweko5nrHtMco71hhSYMnSp1DVJGKNqYBEyD2AODvCRbb/CMcVRHezXpBdrP9DmcKJ5lyJ9o6dhDw+3AMieE5meoPzv9BnMIN9gLw=,iv:H1MTwW5QN1NxSCvYAyf/p4Nwaef+SVCxGLmZaRLOMRU=,tag:2ruKJo8d8lQxPWy1rZdFPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
