apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Vxm6j+YzQwFCVEg22ak8a7eJmIP77rYNiHoHY3RlrHwFTndGHi7GyRZoZFsBkOPUJrhnNMvnFcIutYUXa+nCQBy6lwbxJNK943Hr3yJAwDsL8e0/9NR7w4XrD1BJrPGuKetIJxqMY9gY++957qnOe/m3gFbKrXFNWBC6jmbeVRxccemFXyxrEtNlWQMnMgUAXnFnwlPyVPWT4QbL9h5nO8aZX33xOfaY4tOBSizIbL9EB5+4,iv:qu5ZJlCva/s+V+8gEhDHPI3aKohxoHWe0tn1EdPmwng=,tag:j3XcSTY5TH6LUakCCTB8xA==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWHJwRUtLRDIwOWZJcHNQ
        cmxVbmxpL3NuQ1JCMUtKSWMwdUpucHN3QjNnCmk3ZVRvOHVWU3NyV1Axb3B2V1Bp
        VzF1UFVHS1hTRjNQN3gyd1RjNHFmWHMKLS0tIGtvQTUwVzVEN3RKQzBGZVpMN0ds
        cEoreEJmNkZBM2RQWTZHck5YZ0kzYWsKfJ1UQViFYNWzrTtcYiHR6vl7BNBPiUn7
        e+Oh7dROyCDloDy1JNn/F2zSN1l5D/Kocd8KUScKFR2Fe4hQkguxkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T20:42:56Z"
  mac: ENC[AES256_GCM,data:90MVZRs92/17JEfkCkNE0jQvu4AzKMu/Zu9PnKfQJ8GHKl9aPM1EgnVmDTfz/Pz0Zo81+WCdJBWKBE/8LDo9tJQM4J4rxdXMTlC8OTDeDjbMQUQmtGKDRCeMl/lsNilC3sRSH0q6NVyZmg647ctLlUdHreQv0Ht9oLFUJl8Z83g=,iv:YDmjzWFklFGQKgVxRiJiqoLqayqh5betc0Ghl5HwHV8=,tag:kC51+vOnk+C/Cs1qfhw2/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
