apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:nj7q8hfhzFK1O54hjxqbmgfU0tOXVNye4ATJWP6phHaNDXJrsv+vYgZasnAlisaMdF09ZEYEScFp/AauHNTLeu87wwErFcVIOqzYQ5Hc2rBZVwMJEeZZnZsDDHiO7mZdBqNxOAynVoAu8ipc8AklnHVIDynkQrYoJTZJLq/SZU/jfoxlykF3bvK1OD8VtMDNSK2T6YmnXjWONroxn6jE/EODkURjP3bmmc+tvVugxKQ59Jui3aIqvKWEVzfIeUkgT6JCeYqK9qpz7xTX6YBfQRrKSHEAtVkD+nffG8/Fe8RsN4LerhY1zSF+82CiYrl6xtTgjGi3iMiUuBtuQPEUW5qBX+tePgW+KTDkju1gWoIKUfIHPEZ8wcIzetEKvl+0MqbxKXnY2uHf/Dj+hsGcJ8e2a0RK+X5M7TfSBdWKo5VdnV9SWz+/mfJYhAGIgfoiK/TNTdFU4hpFdRHdRnl8KKSIzkbrEPrm4ScGx6uTjfvY99oHz/tlHYNEpCyTk1/1FKwLTBn+HPWyKpdvD/YghELe7i2hqTHftHLnOzvC21+iCk7sDPMdWvbFh0TGVzyx/Kfp/CvkDtyfCa2lzaeSNECMyX2VPJ8RKoFRIBK2VwJ9yhAwPEZPcwISznHZ3H0975Yrn0HUdXFiDACfUOtmMKt8jFl4Dyh7RmWeHsm8k7Chyoiru84+ChpjpRT/fj9nuIjA2ebxgvtfORtCwQTtRNeHICsIXV6iJadE0i9Q/EhMp78HpZ08/kJTZpFCuZ0AV50akX0oIhFjPODkb6ZTVnrKmJrvytYLYIv/oMsJ7CMmDm4mN3bIyxYTcsyABDqA9TOiB2KOx+mAOMNNRzb/Wp+g,iv:VkvGwGRfchN0AgqYPxukF6IJoquh/06TlHd2BvsupeI=,tag:E/N2MVaT+nINKZblLVgmhQ==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbSswV24rcHNROUlpSXhM
        Vld2WDE1ZXZrUHJlQk1vTHVzNkJRZ2RSQWlFCkVVRFRoU1IzRWdoZ1kveTdQVHJY
        cW5KRGwyYlZjVllqR1ZXR1JSdkd2bE0KLS0tIDdhVG1hUUVRcEJUSEpMYTVFZzl4
        TzhKTDNhV2thVVYrREoyWTRYVE1qK0kKfXkjE4LlEhJ6aokHNw9NHcWpaKYBTFJH
        6jrrnjQ1AGVyOm2qREbKYIiQeuW3MoCFk5gJNy/byIPbxB/zDkBXVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T02:03:30Z"
  mac: ENC[AES256_GCM,data:uqPP3hWLShHEVZ43oaEsFIGyOzIB1PMZuASGiZG5YuQZ99k5vFcJUwjLukagRotVjSArEV3UOXiISQzyGw3YyOvkyrU7nFHW2lUhKuapiN/9HupUXGNRaPFfyG1J/vG79cul6pbehTV43hK23oENIFMn91R8YrnFeb6FlmJ1o9k=,iv:xde7UisI7mcRjHDSEs9ttxvub4O3M0ABP72WPfB4UtE=,tag:5MQFMkcae/crfCvIhOcKQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
