apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:Yo85ML3LLVH5vUnzu++UpBEQgsx5ESfJwdcekUVZJNYyiq5v0uOFvgpuV95eMt+jY/ifuJKzo6o80IFWzTVCmUkj0tRKtQ2kzKlCw1rbtZEVWKY2FKL5rYE+DDDaxPbzzIHW5toz6S1fabxRsruQnyhMRhyN2sxKSubwi59oidaCkaqyxj3ImRXl/NIuUc9fDEyZLIED8g6oTlbXzrL2ayfS4nxcEKdPKXcdhkTfUxtGga/DV9UZEeQsvaWGeVtj9Y0RwsfMMoj8S3U74FLQsvH+Rbw2A/ApXLNQT19k1j8UIZrSBnOaDIDK2LdDKXiFZGIpzg1hSUn9+EKZUefLbbk3liYndwSdwYyA0phpYLzoefXG/6+wD7ESBfOjjRQYWi1A1BceZHRacGy1OhLIikE/tIxfeM5zy2GiWSPiP/EQ+ihs3KDVE0Q09InX7Womoubd+t/JLbotvpUsTEKXtlpsfettratrZZMpz3btLAzaavuy1qzBPj12aVTj75KAAjwK91kk6Ea6UjU8RZel5U1RtG3RwuLUX7lKbSQDQG89VIfwU1GVEppApnD608zJT5zlvyrr74aHz2D241IVc+4UcK/4T+2Ga8Fi6ODRqb9fVOW6KwThHKR/tLB5a00WwIbvmIgnyYOFcYDPzgO37RL9sWJmN2xD8NmzkwSf6ukGd2Sge/PH6o9y+4DAT+AD0d4ZMyYq/aFNseiTuALjAStRMNPCEOEOHA2tZnIHt4eM+u4bXXkBPY1YeZVh1HYjxYCB/VaMIK3f4JJDNo45Tb8/UwT0J9ZwNC8D5a6uSrpBDZ1tEBu/axWXc54aeQ3B1UD1urM6Dy6sS58yRF+HSYuD,iv:6LQpBn/AwcLCQckY+kV5XRWs/AJtZW8P80Ix1CIb62w=,tag:cu9dGJGf+u2jZbQ/hdzvrw==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeXBWQTQ1MkJ0dnEyUVgw
        ZkI5c1oxdDF0LzVoTFNGbm91S0NQYmhqS0F3CitFcTRCVVVUc0twaEw2K3pJeEJM
        aWg0aUR6eTZyZ0RzVFRRYTNPaGw5ckkKLS0tIG5YM2I3K0x3QWNkcG85ZkU2Vjlp
        UUM2Ti9HSWI3WmM4cGlCODZKY0tFVTgKcoJ/Wob8XaengT6tNg13QwI6uwiLK09s
        pBdTszAMm375XrSG2qExvLhtLgMLlGSKQPenBSS3c+gWPsZMEKmwog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T03:31:54Z"
  mac: ENC[AES256_GCM,data:M5HyAU2LyupQUlpi3a1sBYv4xy3sAmXKLQc4Wqa+tqPEqjVHYWJf94e8DijBlzYO5MQiM+3VEGSOCD86dn9VXWN4fPvb9bta91yvG3uo/CDXi2XpffqUUkLBf1nsSJ/scBjSAT4RxwNqUnm6KTK6M0dfYEYwBVligs0v+rADmgg=,iv:gaS8y6BKkyyNHZFTw614nnKGYD0WOyXX0U3DUxW64H4=,tag:fbrm1c1p0eZFqX+inSb1ow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
