apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:yEj69iv/YFkddtv3K8ptceLgAVJRPJ2vMPrHNqwl8TscoHTa6RreF4nnJQbrzYl8M/9rBMAGjg0KYT5oGHLFwlzQKXoydT60YNpNwSNGB1HSuBYkfHcifGazArSnnzi0B/HAPfotA+wYrWy0AEcMV55wSoaCyRMRGEptKH/e9ClyCgDvpZfk6MOjwTZ+6FgleoVDjOAITWnFLWALAXDNCedmQb/amyIbms3YsAR+f7hsgo5panySqFnfbqJ2bZZLHRwa+5wchA60YOEg7eMfs4GJvdgycewGyJPXisgTQOZHS94xGaSyXx/Sn3vzWiOXWS+xOtfzPOrQFEry2oEOdXcg5Ovg9mtOaMt+6uGmVhQaU5FNAe+LnGCsp8pZiHPoC3fZ0nFQtF7J3wiHLFw8tul9S4U9TtRbLFgIM8Zcl3Sh7VuogKM01REjmTBJfkFkk2R+EWiKZ3v4SjImbIfpAV5LBQgl0WZm3GWlA2D2JLJ6O4dk7nfAgNQPXbGNuvqYAnS2NypJvmcfLC12RkyGjMkGTfOx227K6I0QdpShT4vML2LI+rAXJ3ODVTp8eZ/RyYqyFST1WOWtJwodd/d6wdeZeKHP/VlVdd+raG8qE0QzOIC5kXvknD7C24Bp85ukWmXGVot4+cIrbvYCyD4x2Dsd9HVlZJxPBEHO+a82Z31eLDaw6PTXlnilsjIPCW+2lvl+feF+K1JPCxAQZvncdV6jD4PyNNUmekSIMZ+7pMISz3uYaWnd6u4/VnOqaAKYTIR8rbuUVXj7J+7AFRXgxabt3o5He93WqJHWVWDrF3dOJFQ1OuTNCiYrxoy/ov4AKKanG1Zf70cR3oUMgf/czUux,iv:BqsDM0ZSQkOYK9Ur7o0wiKvH/cQGwbLJY3O/9e2R4nM=,tag:d7XxDDHLAMDuO1iuSbtmGg==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeXBWQTQ1MkJ0dnEyUVgw
        ZkI5c1oxdDF0LzVoTFNGbm91S0NQYmhqS0F3CitFcTRCVVVUc0twaEw2K3pJeEJM
        aWg0aUR6eTZyZ0RzVFRRYTNPaGw5ckkKLS0tIG5YM2I3K0x3QWNkcG85ZkU2Vjlp
        UUM2Ti9HSWI3WmM4cGlCODZKY0tFVTgKcoJ/Wob8XaengT6tNg13QwI6uwiLK09s
        pBdTszAMm375XrSG2qExvLhtLgMLlGSKQPenBSS3c+gWPsZMEKmwog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T19:42:16Z"
  mac: ENC[AES256_GCM,data:ENDXLCWgTn8a6nyaVd/QN79Slwy4gOoEzN5qMdxQajsUxywQcxBJddbcObOuwgfEWUbfgWMKYKmaVvI+r8O/DiFsWrokX+4/icjpbLK91UK67o6xsR2CzUIyeLuCaEsBUW16jAlkvhMKLaO9jEbqj05fu1/ZMV3uVy5IpYeSE8c=,iv:2/XVZjcLXB2ttT938MS/Yp+cqCvuo8J0kLESHPGmaJE=,tag:lkCOvtl0YIG9ERtIx8UWjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-credentials
type: Opaque
stringData:
  1password-credentials.json: ENC[AES256_GCM,data:PcQejeW+lXhezmwKczwd6ar9wPmSoI2wSOF5L7MfOamj93p1CU3DV6jVGAAelGn3gTevtnFGZEmBNqp09j5tC96tn7cHwoRF9HfsFy33yqdsqTL56EHhpH/SIgArrwA3eo0gSpvr0mfI2t4rN1nswIN8QaigWxsa0OqttFJ8MTT/w7GrjRXRyEeKvQZG7wO8eKTXL8hgECEFsyvnIk9wRX9e3REfJxAMQYYpmq7zVCdXrJtKv4cwDN8LNVRUdD8boRJTg8+NeatdymIrRAGOCQTdyqMflvVcQDr82zjLuk5Clvchl6Xw5w0VJEJuq5hIU36hPGCvojSIRnHjUEcM0ES00rbjWBpl6NJ/X5/wh6Rn/iNJngv59Xz+NlG40jSAzckP3q2D/idHS3W8nEJAdZSPtfeH4Sgv2QR2B3QKUrynYxUjEd11azI6rvnlDGdd8xEWphHLO2WgOo+XtUMhqZzlwgYWTBcMRIdPUUhK6RWaIQ08HwgI1cI9OaGL2CbKirm9srxG6hof1J34gzvHYG0+VflLaNK3LpznYrmKphC/4VJtvO4wpCgOqf9ezmHMsx8jJwS/pMpKC/+pHs2VAO/4O6qW+xfpehp+txw2ZoHtOfyWQ5+2gxlmdcoE3Ir/H+yN9N/UubjaGsIC7/oUPmH3SWyoHgDCLEhO6sjbiyYs+9lY00YJhA/ORD9sOt8Cdj1RMwWx757PRkEUmEH/Hjy2eolK6Iwz4j84G9ig8dOCXNSRu/ntuE4EcZOVBcBYX8yEtZFoM+QGgkMKjVNwLuAmLLEjvJsYgqqyCLrVXTNUtLvbNNQBx2taT5EC53LfMK535XZNK/oXEMoH+96IYitv46HK7K9sOzSxOC8vI11w13VeLXBQ9prJpGYFHYAF+n7x6T9tzsbjNb6K1rd3HrbwUmlhHRFx6jrrY7ZSzUXQyydxXw2DTLw3gt0x5V9j0oU/mnMsMH1GRamSQqyy16W3BaNt8sXEumDPWuW5JtgTzKUQOXhMAV6x79IM9prjdr66WloiFuUbqou/DsdnrZNo6I06o5k5Sc2RYlxmqelja9m3PCoTSiK2OzUuslwEGJ/AlJu7631cIk3PJtZ1CEx4hJksF3Xw5VoK3xfNgjxYsK/JbvwFdhe7I8IME3Bqa33GJKBjW8Fz4RLTGwcxao8flCbIJnuBUinMO62X9Wf3EEjD+lobvwtHVwuxnTGzECeCqrOD9ZfH0L1tt/npit/qVXYI0qgDLBXrtvF2bSW6KWaWlpM6Lcdq4JGCc2BQCUTh/yNHSrwgrl4s1uKwFaWUwK+ggbXfTVAM7X6q1521e7t8x6aO0MpC6B7TN/5Wz4MzYp7gLgGaqLYugGAhwtbjonXWmcLDcWdcF4c2rlDTN9SqpUiFLMxC+vCNdXwG+t4wLAU0xsegVvGsZqcHXT9vHe5dST6G8zwntafKoQHaYcMJT/ZPo6sX65lfmN7vAT0mDVksiUmZY+N6QUISNRUPTmsGiAMgXdkCz3qrZNpVvPWd7OqNZAR4nj4q5YorWNDY27uW3CbOpYTfHwiQa0nbY6XsyOI1wynQMRWtSOHbPzKKcx6NUp9lZUzskqjs2eSRKFc73+ltCt/w/P6XwLuVBempaKBc7NWpUdV+Pko/2hgQLFgQuBOg2C+14Isn86CvEqfGHzV5hdfZ4Q0Ntaam5tDmvO/oGEh3UjG+HSAWaX+n+IGUHw3CyQR4DxHdEGTwlzkInUe9G/fy4T1EstthT6/JIYUpI8e3Dixh7h6Gnmm+LZOQQLj+FsJx/aLUPLh5XRL5tOS4kVFnCYrYxBaq5nWMwVpD3h2ggqnJFe/6mBwi/LXMrNUlMlJQxuvuqxL6AQ0zJCEz8ctHkIg76OaMjiEoejfcda4p98Z6Cmm5GGiOnsx7YKixU42NrDQoHS0qNlfaKs3rbpZb,iv:LlFD4f/dBagyBFAmCTzFUfOjIuIZjUEAhfE0A6RKOv4=,tag:kIBAbccg09Xhl7G1DLhnRQ==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeXBWQTQ1MkJ0dnEyUVgw
        ZkI5c1oxdDF0LzVoTFNGbm91S0NQYmhqS0F3CitFcTRCVVVUc0twaEw2K3pJeEJM
        aWg0aUR6eTZyZ0RzVFRRYTNPaGw5ckkKLS0tIG5YM2I3K0x3QWNkcG85ZkU2Vjlp
        UUM2Ti9HSWI3WmM4cGlCODZKY0tFVTgKcoJ/Wob8XaengT6tNg13QwI6uwiLK09s
        pBdTszAMm375XrSG2qExvLhtLgMLlGSKQPenBSS3c+gWPsZMEKmwog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T19:42:16Z"
  mac: ENC[AES256_GCM,data:ENDXLCWgTn8a6nyaVd/QN79Slwy4gOoEzN5qMdxQajsUxywQcxBJddbcObOuwgfEWUbfgWMKYKmaVvI+r8O/DiFsWrokX+4/icjpbLK91UK67o6xsR2CzUIyeLuCaEsBUW16jAlkvhMKLaO9jEbqj05fu1/ZMV3uVy5IpYeSE8c=,iv:2/XVZjcLXB2ttT938MS/Yp+cqCvuo8J0kLESHPGmaJE=,tag:lkCOvtl0YIG9ERtIx8UWjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
