apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:yEj69iv/YFkddtv3K8ptceLgAVJRPJ2vMPrHNqwl8TscoHTa6RreF4nnJQbrzYl8M/9rBMAGjg0KYT5oGHLFwlzQKXoydT60YNpNwSNGB1HSuBYkfHcifGazArSnnzi0B/HAPfotA+wYrWy0AEcMV55wSoaCyRMRGEptKH/e9ClyCgDvpZfk6MOjwTZ+6FgleoVDjOAITWnFLWALAXDNCedmQb/amyIbms3YsAR+f7hsgo5panySqFnfbqJ2bZZLHRwa+5wchA60YOEg7eMfs4GJvdgycewGyJPXisgTQOZHS94xGaSyXx/Sn3vzWiOXWS+xOtfzPOrQFEry2oEOdXcg5Ovg9mtOaMt+6uGmVhQaU5FNAe+LnGCsp8pZiHPoC3fZ0nFQtF7J3wiHLFw8tul9S4U9TtRbLFgIM8Zcl3Sh7VuogKM01REjmTBJfkFkk2R+EWiKZ3v4SjImbIfpAV5LBQgl0WZm3GWlA2D2JLJ6O4dk7nfAgNQPXbGNuvqYAnS2NypJvmcfLC12RkyGjMkGTfOx227K6I0QdpShT4vML2LI+rAXJ3ODVTp8eZ/RyYqyFST1WOWtJwodd/d6wdeZeKHP/VlVdd+raG8qE0QzOIC5kXvknD7C24Bp85ukWmXGVot4+cIrbvYCyD4x2Dsd9HVlZJxPBEHO+a82Z31eLDaw6PTXlnilsjIPCW+2lvl+feF+K1JPCxAQZvncdV6jD4PyNNUmekSIMZ+7pMISz3uYaWnd6u4/VnOqaAKYTIR8rbuUVXj7J+7AFRXgxabt3o5He93WqJHWVWDrF3dOJFQ1OuTNCiYrxoy/ov4AKKanG1Zf70cR3oUMgf/czUux,iv:BqsDM0ZSQkOYK9Ur7o0wiKvH/cQGwbLJY3O/9e2R4nM=,tag:d7XxDDHLAMDuO1iuSbtmGg==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeXBWQTQ1MkJ0dnEyUVgw
        ZkI5c1oxdDF0LzVoTFNGbm91S0NQYmhqS0F3CitFcTRCVVVUc0twaEw2K3pJeEJM
        aWg0aUR6eTZyZ0RzVFRRYTNPaGw5ckkKLS0tIG5YM2I3K0x3QWNkcG85ZkU2Vjlp
        UUM2Ti9HSWI3WmM4cGlCODZKY0tFVTgKcoJ/Wob8XaengT6tNg13QwI6uwiLK09s
        pBdTszAMm375XrSG2qExvLhtLgMLlGSKQPenBSS3c+gWPsZMEKmwog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T01:45:54Z"
  mac: ENC[AES256_GCM,data:LQZGgpxIO6ePsxcY90ug9KDahYa8PjdI2Jge8s3toOXEp0bWUWUJ0OA2gxS/+umW9jSDHH53YdDG08cfA4OvdKtqVRddiyYtZ0KhzK8UYOhi2obHaUwarAEJWXSF6lPgp7GxIkoJFodgnZRu6DBJjG4OBgeI+1eqMPLaFYnxbsA=,iv:Ao0gGBUixa6Azbgv4fKluKUhvSuCP5iGsVAFij8BF70=,tag:+9HdhxRQxFV2w34qnmnUJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-credentials
type: Opaque
stringData:
  1password-credentials.json: ENC[AES256_GCM,data:VqxmIFbnih8LACBYoU1pQHpu4pJ80bnF4uxV9mikwuN/2wqTsynwJ9bdBbyPF5OzW1M1IQUe86Vs+sZBuGODDaWVnjE6ws+P0cbTVUjdHOyj414MGRNW5o9J2EpoBjdzqrjpHC+QR6pMqewFvx+EnXJMo+so6uyR8inDxAV6/UoMBj6OoYVM642tWkBMNbnJi1O/lwsxlKr7rvxhkr9ZeOpUljY/gPlhSqr1KCWZQykeuzZohXjYdW0dpznXMJbUqit1/zid+VnJyP7Z3mbjeRtd5zy5fGLQwvUE4YSc4h/GF5Cjg7hd7H6Bs0bpj41dhPR09b+Lj93nA6F1EhzOOz6t2VbAdpifJMl5Aw3Ht6VFUOx5kraQdpzyxIeYZ4yeIZ1H4kFeQH2nKSotLbphs1XcOpwwgd6OZNsM+HRnLZrd2SYl/fMZWIqeWIY0QodTV8bFfO4gN7Ul3VLNRmNnCymsUCs9lfRdaOuP8CN30XENF41GlpGKftUgS6QDJOdh+1Hez/o+UHoDsLZ/okU87Rv0XGtG4Z12rW2v89GK/0AOLEulVYSNAJFWRyosk6BLOP63WPdYUCO/ritWBruXGXkubmaj7MrH1I9M36snrRT0ocelIFUd2/QlYRIA7lltIlHGulh8YSBExdaAijWcCu80QSqbcNVCYO9wtaXSVD8wFHgPbvPS8eVlPTiGA/RT4uS3lPoSI66olV69UzCqG3RWz76U774SCN90bd9hW8Tq85hrvOyGWLwaXQpf65u6FswY82dao61xcVRSfZi+S4XCv8ZElHY3Hom54XCCSpXQQ0Wijz/1b5T1VJ5ubDdwtxPvl/sPg0tpQBaxjRpGnR2fiVNnJZxpoi93fbygIVh5IcXcbnKKD3ldHmdbavNzLoT/6w5ssoMzMWsl7wf3V2nsiuWDwZSs9Qg2jMIp5DwKYa5rr3g4TzxHB9hOXya2/zcRczbv2kD6NL8BfKrM1lrPMu95aSNIyldpQdadTLNrHvMbbt8zVRAa8Z34vwmR3AFON76oddYYia/kRwuuS0kPAiNDlPZzDJRu3HpSMwKHse6L0spCRXpqPmhs7P9aXNgGOaNzQedNzt6j50koHVi2/AEBUPIiUqt7CMPukaJddhYk+fpJJji6UewvjyZtIXhOQfK2agU7uO11mKYR14leN57vcfIf02B3tl7nR43CFcDWQKlWdvfkCMxEOoHgTC/4gM3qp5JOuEiFFRKmmSSV7hrkGmq6N3H7jOMSz/EBkJUlwSg5vsdJJQdW2JgR4IEww4gan3OGKwzf6UEN9FFa6J1T/MsaKa7mEtKnlSZzWKaGgrc5tQ8MQTc7u87VWKsNn5XwPyyuC9hOkf33L3hsoAaysMdLefpXXrDdvb7qjkP3uObtc+Rh9bIgDkR193R16g8BW/7XSA4L3huiX4tQHXITFsQsFxPt7PkIsGg=,iv:HPdodvxOOpgzUejjtC2E4WH7ifpUCQzXmKVPrSV0wj4=,tag:3fDzUKQdvO3MwcZ5d77QJA==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeXBWQTQ1MkJ0dnEyUVgw
        ZkI5c1oxdDF0LzVoTFNGbm91S0NQYmhqS0F3CitFcTRCVVVUc0twaEw2K3pJeEJM
        aWg0aUR6eTZyZ0RzVFRRYTNPaGw5ckkKLS0tIG5YM2I3K0x3QWNkcG85ZkU2Vjlp
        UUM2Ti9HSWI3WmM4cGlCODZKY0tFVTgKcoJ/Wob8XaengT6tNg13QwI6uwiLK09s
        pBdTszAMm375XrSG2qExvLhtLgMLlGSKQPenBSS3c+gWPsZMEKmwog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T01:45:54Z"
  mac: ENC[AES256_GCM,data:LQZGgpxIO6ePsxcY90ug9KDahYa8PjdI2Jge8s3toOXEp0bWUWUJ0OA2gxS/+umW9jSDHH53YdDG08cfA4OvdKtqVRddiyYtZ0KhzK8UYOhi2obHaUwarAEJWXSF6lPgp7GxIkoJFodgnZRu6DBJjG4OBgeI+1eqMPLaFYnxbsA=,iv:Ao0gGBUixa6Azbgv4fKluKUhvSuCP5iGsVAFij8BF70=,tag:+9HdhxRQxFV2w34qnmnUJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
