apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:dVtRowcLi+rg9CJGxmhx75Pg6uLSLG8/1mZPKb2ihJkeQ94PvC4ds34zL+f5G9nK1jue0AkVV2w1KrlFiYa57Y4P5421W1Qoisl23qx3WRTLozsqjlks4J82xcViSLUEqTaN+EKqiKDAIYTOkYn8HHVjzWQx8bXeA46uiNk1IONRMSkLBJ0qD5Z+bBDfFIJccMo8HQtXx7Vi3244lV2lbwMeaP9v3NlAncRz/NIoKKXN02eABdykicCoGcQZstUlPf9oyCe4NzPcg3XdhSvXOQv/+Ex0mxon+P0j7aZq1A0c1mJHDKKkzvLPBmFe0x9RdS/j+7g8oiyGhuqT6J83idRzjyweOsNu4zXSw9g6aF13ggqEGTFAqFeEtpe4Il4iNxiac8QNtm+0yy44Iap5Q9UlGw3YuaIAyXUEh6Vi6OwEfEQJVarWEV+5DsSllE+ubeHOxpECvDgmlGc4DjrgF5N8Ndah6pkQdn+4NXEAPW2tsBj3i1QzeLSvHh/2OgJQaGIIk+Q5ja/BZd8472luUhYEBmhou1pAnLAfry0uMFq0l0i46bOw9i8FGA6g9dwrbemtKzgx19XLM6MY40LM9EtmoDh8tDipMAcY65F9qIqmi2VAuya/c2PDIK6UJJUxCot/e3VjmY1b8d4mapgX5mt7LqoDGwUTep2V+xSJHWv+sZY1k8YqU1No45UiyUCGKWYjAOSPe+S4VSH7A7RikbitDSP8Bh3qyhHKWOLWPqyBEt00IZjFMRPQswDvVouFN8h1LuQ5siJq6iaHbmXjObJbbrtqeBY6dirv4nZb8H7GyJ/Uv9Bzt4oQ5iXHVb7WxyQTSXznTjQMjQjj9EdLSEum,iv:gfppezEeGeXNk5NztHCM9faxz3NDI2MFg0h/e9bYBEk=,tag:Wwn/wFrtqzwTB5c/ZfeoWQ==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTllWM3k1bkp2bzRGWkps
        RjNCYXUyb2lpZG5SK2N1Y203YlJYc3lkN3hZCnFVa2Yyc2tBSEVwZjFFdENMY0wv
        c2hwd2RmOVEyL004c2lWR0RCZm5xODgKLS0tIGlzK0dBck1wSkM3MnB2djE1NU9O
        M1gvUGZoa256T2RmRXN6VHB1L0s4RmMK+ysmhBcWbfdqo2nDbP48Whf7tlM214jb
        otvhlN2ae4VhbqCndN/XXk4aloXGz2WHwzfIxRxtnABOzwkXeja/Xg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T20:42:56Z"
  mac: ENC[AES256_GCM,data:gTWDkdIhdsAhfS7Pe5wnE4XanaHpmGPMhVeNxqDJeNrCaJhGONAhT69Rxpmliqspx2Oyz6+44nyHFGvvhuc+r1j49mLPM2hItcRoIT7m3ux4SIZXt8060kyvaq5zJOLmiWkznN90DLYvWrbjAzcq4zTWCVjDY10eDGUQpC9DKnA=,iv:AcQz8/7iZ2I25W0hNa/xBJD8Ldy9YZamTTwTDWoty70=,tag:+bvbu5nkAX5hwXqCbkE2SQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
