# Immich PostgreSQL superuser credentials
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-immich-superuser
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: postgres-immich-superuser
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: postgres_immich
        property: superuser_username
    - secretKey: password
      remoteRef:
        key: postgres_immich
        property: superuser_password
---
# Immich application database user
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-immich-user
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: postgres-immich-user
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: postgres_immich
        property: username
    - secretKey: password
      remoteRef:
        key: postgres_immich
        property: password
