# n8n PostgreSQL superuser credentials
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-n8n-superuser
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: postgres-n8n-superuser
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: postgres_n8n
        property: superuser_username
    - secretKey: password
      remoteRef:
        key: postgres_n8n
        property: superuser_password
---
# n8n application database user
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-n8n-user
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: postgres-n8n-user
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: postgres_n8n
        property: username
    - secretKey: password
      remoteRef:
        key: postgres_n8n
        property: password
