---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unifi-dns-secret
    template:
      engineVersion: v2
      data:
        UNIFI_API_KEY: "{{ .credential }}"
  dataFrom:
    - extract:
        key: unifi_api_token
