apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:yJ5e39vdZ0p+ZnRppTbwRZZRVUkAOfk7myLsEib1Evai9lYHX8XKdQ==,iv:rPib6DL9lYn+GdssOGnFnCT8GFaX5hyk7tt+bPXkRIM=,tag:bPVsa0cKkW3SfDAofeDvqQ==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeERFbFFKdGErOUlDNHpM
        ZWovRkFKblg0Z3Z3NDNmM1NFNUoxajFlZGxrCmpZdzJTSEF1L0lvZXlrb0hKU3hp
        djM4ckRacjFZVkwzMGp3WkNnUWs4UU0KLS0tIERPY2hnTlNtTkE5YWdla1cydUc4
        ZElsOEhQd0VFNFZUQnE0TWNGaVdJeWMKxOomF7WiZfQ5ZWV6AV+M6oq03qxftN5T
        B1dpY6AR7w9YV2vPJWBKl28DHQdStSZF4EdK57RYOULX8xbyeUlgMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T03:31:54Z"
  mac: ENC[AES256_GCM,data:+Wg/qD8RSfa1pG0HfxK2QpmJu+pkfz70nhbts/MsnP+ZfQGh32e64SaWKojA/C78V9o6n4NOXIA4iQUu12wRvEo1SKaEp60ifHS/XUPvhGLwbbm6bmbT8Fg3hlTRNMvyU4Dj4WQY8bAspzCTi+iwJNrsBj9aMjjGvBjihj4wvo4=,iv:abpHKgetYDwfs1Iz0kH921JcomQxN8b64Y6ANTiBjws=,tag:Ym13Hm5soaMOzwJXWeMg2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
