apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:/j8VL2mVaSkpHqnwAp8RYiTr9Wu/zQoWcl36KMXh2sae0E/QKFDlAg==,iv:Y7eSrUndeeTLfWysfubLgI7DYALoSRFHKB3vFcMPwCI=,tag:OT3IHpMUgzLNjvu8OzPhCQ==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYzRnYThhWVg0ekM5dTdK
        UHR1Mm4wZGsvaEtmTXJuckxhOW5jQmxkd1VvClgrNkxtanNrNmdFZFAraVVPaXJ3
        MkE1NUR0eGhuQ3cwbThDem53Qk16QWcKLS0tIHBnK1FmLzZuSldVaUVheFJHRndM
        eXFJZXN1MHdHV3hEQVdZemcvMXNJcTQKHfCJOicvLARs0Lg4EfCzatAk8VzUNAk4
        vpzCdJojzdQXIAX7TwP3+iLjcE0XbTOpBj7vmb+TY7r+/+WCQOONNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T20:42:56Z"
  mac: ENC[AES256_GCM,data:BMRampl3/Sp7UvNCBUPuDuivvbvTPvG1xsNkh1+Z0XXzmkqeJO8GrGwOnqTx8BldHTxDAhHX+ZPqOJXAoSYA77wyTEHm/1fvVghwufxE/BiYnCOn2985TYnd8EU+32XQJ3hFwQ1eRygaR36GupV0ImzViquTL9NTNRSL+Yw6EXg=,iv:+idKRB2cp7w/i8abW/av5wpb19fGDbbREDtTwKghKXw=,tag:1Frxe9fkjuQDjLwkle8nJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
