apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:LNIMQs2HVIgzL3D0nXTFkEXHfcKWrmKMwdmupQjJ+Zs575WrVjBsow==,iv:PsjRDxaiReppspuOfLqc0cEO5hnSA7Eh8AEphMZJQk0=,tag:k+zE/Oms8pwwmMLBiSwQdg==,type:str]
sops:
  age:
    - recipient: age1qqfuvdaf3j7uczq5hjjg05074k4wyz0v4dg0luj4dza38vng95ns67feq9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2V0dNYUc0T0h1aTVwTDYz
        SHdOR0dJcllSV2FCc2tuK29vREJFYm5oUGpNCnRWOFlVS2NIclp1ekZ2cjkweGpq
        cTRLT2xKSlRjOENqZUN0dWlFOHNtbDgKLS0tIE9GaTAvWmJlZzB4Y3djdTBhNDN5
        RXBIaG05RXp0WGJyZlNOR1lacTVuSkEKZaU2uu8yz1vQNQgcx04FmxreDb0KfYlS
        Cf2PPoZtHwQylrgu50Y9dWmaEEqGTBfUS3aFNIzqYbxnl3IR+FxwuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T02:03:30Z"
  mac: ENC[AES256_GCM,data:LYVo+bv5LZg96EGyc08jk6EK/aA5uIQCuT0x5Qqqgk58PNV2FKXIgXMEXOf07SdHMlDTaYiFD4dZUimvCJEvhP6RdYAokrsI7PgLyOWhWK89AEzxYTwEttA57hLaVDujsAhB3NvWFrmwaPOHose14/AIiFpTPQSEeJbC2Dq1a5w=,iv:f8ci4/vE5ajTLjT5oav7FOO+YOE3idVN5qT/lGjq77U=,tag:SVFit6V6LCwmxkVOMc0pXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
