---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.20.40:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.20.40"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-cp-1"
    ipAddress: "192.168.20.41"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:44:7e:35"
        dhcp: false
        addresses:
          - "192.168.20.41/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.40"
  - hostname: "k8s-cp-2"
    ipAddress: "192.168.20.42"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:0e:df:76"
        dhcp: false
        addresses:
          - "192.168.20.42/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.40"
  - hostname: "k8s-cp-3"
    ipAddress: "192.168.20.43"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:ab:fe:f5"
        dhcp: false
        addresses:
          - "192.168.20.43/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.40"
  - hostname: "k8s-worker-1"
    ipAddress: "192.168.20.51"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:73:1c:55"
        dhcp: false
        addresses:
          - "192.168.20.51/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
  - hostname: "k8s-worker-2"
    ipAddress: "192.168.20.52"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:75:a9:bc"
        dhcp: false
        addresses:
          - "192.168.20.52/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
  - hostname: "k8s-worker-3"
    ipAddress: "192.168.20.53"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:9c:cb:81"
        dhcp: false
        addresses:
          - "192.168.20.53/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

