# TrueNAS NFS share for Immich photos
#
# Used by: Immich
# Contains: Photos and videos uploaded via Immich
# Share: /mnt/tank/immich
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-photos
spec:
  storageClassName: truenas-photos
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${SECRET_NAS_IP}"
    path: /mnt/tank/immich
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
