# Static NFS PersistentVolume for TrueNAS torrent share
#
# Used by: qBittorrent, SABnzbd, or other download clients
# Contains: Downloads in progress and completed
#
# TrueNAS NFS share for torrents
# Share: /mnt/tank/torrent
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-torrent
spec:
  storageClassName: truenas-torrent
  capacity:
    storage: 50Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${SECRET_NAS_IP}"
    path: /mnt/tank/torrent
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
